INSERT INTO USER_CONNECTIONS ( USERNAME, APPLICATION, IP_ADDRESS, CONNECT_DATE ) VALUES ( 'KKU', 'MI', '193.101.145.17', TRUNC(SYSDATE,'DD') );
INSERT INTO rule_mech ( rule_mech_id, short_description, description, logic_subtype_id, work_state, state_date, rule_purpose_code, rec_version ) VALUES ( '63', 'AUT_K_E_M_2', 'AUT_KKU_EVALUATION_MECHANISM_2', '10', 'W', '2015-01-24 00:00:00', '1', 1 );
INSERT INTO promo_mech ( mech_id, intval_config, start_date, end_date, period_base_id, wait_period, activ_period, truncated_active_time, special_day_id, rec_version ) VALUES ( '63', 'B', '', '', '', '', '', 'Y', '', 1 );
INSERT INTO PROMO_CC_FILTER_TO_MECH ( mech_id, complex_cond_id, rec_version ) VALUES ( '63', '5309', 1 );
INSERT INTO rule_mech ( rule_mech_id, short_description, description, logic_subtype_id, work_state, state_date, rule_purpose_code, rec_version ) VALUES ( '64', 'AUT_K_A_M', 'AUT_KKU_APPLICATION_MECHANISM', '23', 'W', '2015-01-24 00:00:00', '1', 1 );
INSERT INTO promo_mech ( mech_id, intval_config, start_date, end_date, period_base_id, wait_period, activ_period, truncated_active_time, special_day_id, rec_version ) VALUES ( '64', 'B', '', '', '', '', '', 'Y', '', 1 );
INSERT INTO PROMO_CC_FILTER_TO_MECH ( mech_id, complex_cond_id, rec_version ) VALUES ( '64', '5309', 1 );
INSERT INTO rule_mech_config_switch ( rule_mech_id, config_type_id, config_value_char, rec_version ) VALUES ( '64', '1', 'Y', 1 );
INSERT INTO rule_mech_config_switch ( rule_mech_id, config_type_id, config_value_char, rec_version ) VALUES ( '64', '2', 'D', 1 );
UPDATE rule_mech SET work_state = 'P', state_date = '2015-01-24 00:00:00', rec_version = '2' WHERE rule_mech_id = '63';
UPDATE rule_mech SET work_state = 'P', state_date = '2015-01-24 00:00:00', rec_version = '2' WHERE rule_mech_id = '64';
INSERT INTO rule_element ( rule_element_id, description, short_description, rule_purpose_code, rec_version ) VALUES ( '32', 'AUT_KKU_MODEL_ELEMENT_2', 'AUT_K_M_E_2', '1', 1 );
INSERT INTO rule_element_version ( rule_element_id, version, version_date, work_state, rec_version ) VALUES ( '32', 0, '2015-01-24 00:00:00', 'W', 1 );
INSERT INTO rule_mech_element ( rule_element_id, rule_mech_id, eval_or_appl, version,  template_position, currency, umcode, umcode_display, rec_version ) VALUES ( '32', '64', 'A', 0, '1', '', '', '', 1 );
INSERT INTO rule_mech_element ( rule_element_id, rule_mech_id, eval_or_appl, version,  template_position, currency, umcode, umcode_display, rec_version ) VALUES ( '32', '63', 'E', 0, '1', '43', '', '', 1 );
INSERT INTO rule_element_value_work ( rule_element_id, version, template_position, line_num, rule_value, eval_or_appl, rec_version ) VALUES ( '32', '0', '1', '1', '10,000000000', 'A', 1 );
INSERT INTO rule_element_value_work ( rule_element_id, version, template_position, line_num, rule_value, eval_or_appl, rec_version ) VALUES ( '32', '0', '1', '2', '15,000000000', 'A', 1 );
INSERT INTO rule_element_value_work ( rule_element_id, version, template_position, line_num, rule_value, eval_or_appl, rec_version ) VALUES ( '32', '0', '1', '1', '10,00', 'E', 1 );
INSERT INTO rule_element_value_work ( rule_element_id, version, template_position, line_num, rule_value, eval_or_appl, rec_version ) VALUES ( '32', '0', '1', '2', '30,00', 'E', 1 );
UPDATE rule_element SET rule_template_id = '10', rec_version = '2' WHERE rule_element_id = '32' AND rule_purpose_code = '1' AND rule_element_id = ( SELECT rule_element_id FROM rule_element_version WHERE rule_element_id = '32' AND version = '0' );
INSERT INTO rule_element_version ( rule_element_id, version, version_date, work_state, rec_version ) VALUES ( '32', '1', '2015-01-24 00:00:00', 'P', 1 );
INSERT INTO rule_element_value ( rule_element_id, version, template_position, eval_or_appl, line_num, rule_value, rec_version ) VALUES ( '32', '1', '1', 'E', '1', '10', 1 );
INSERT INTO rule_element_value ( rule_element_id, version, template_position, eval_or_appl, line_num, rule_value, rec_version ) VALUES ( '32', '1', '1', 'E', '2', '30', 1 );
INSERT INTO rule_mech_element ( rule_element_id, rule_mech_id, eval_or_appl, version,  template_position, currency, umcode, umcode_display, rec_version ) VALUES ( '32', '64', 'A', '1', '1', '', '', '', 1 );
INSERT INTO rule_mech_element ( rule_element_id, rule_mech_id, eval_or_appl, version,  template_position, currency, umcode, umcode_display, rec_version ) VALUES ( '32', '63', 'E', '1', '1', '43', '', '', 1 );
INSERT INTO rule_element_value ( rule_element_id, version, template_position, eval_or_appl, line_num, rule_value, rec_version ) VALUES ( '32', '1', '1', 'A', '1', '10', 1 );
INSERT INTO rule_element_value ( rule_element_id, version, template_position, eval_or_appl, line_num, rule_value, rec_version ) VALUES ( '32', '1', '1', 'A', '2', '15', 1 );
INSERT INTO rule_model ( rule_model_id, description, short_description, work_state, state_date, rule_purpose_code, rec_version ) VALUES ( '31', 'AUT_KKU_PROMOTION_MODEL_2', 'AUT_K_P_M_2', 'W', '2015-01-24 00:00:00', '1', 1 );
INSERT INTO rule_entry ( rule_model_id, rule_element_id, priority_num, rec_version ) VALUES ( '31', '32', '1', 1 );
UPDATE rule_model SET work_state = 'P', state_date = '2015-01-24 00:00:00',  rec_version = '2' WHERE rule_model_id = '31' AND work_state = 'W';
INSERT INTO rule_pack ( rule_pack_id, description, short_description, work_state, state_date, rule_purpose_code, rec_version ) VALUES ( '28', 'AUT_KKU_PACKAGE_2', 'AUT_K_P_2', 'W', '2015-01-24 00:00:00', '1', 1 );
INSERT INTO promo_pack ( pack_id, assign_method_id, avail_from, avail_to, period_base_id, assign_period, scope, level_parameter, rec_version, taxation_handling ) VALUES ( '28', '2', '', '', '1', '12', 'PR', 'CO', 1, '1' );
UPDATE rule_pack SET description = 'AUT_KKU_PACKAGE_2', short_description = 'AUT_K_P_2', state_date = '2015-01-24 00:00:00', rec_version = '2' WHERE rule_pack_id = '28';
UPDATE promo_pack SET assign_method_id = '2', avail_from = '2015-01-24 00:00:00', avail_to = '2016-01-24 00:00:00', period_base_id = '1', assign_period = '12', scope = 'PR', level_parameter = 'CO', rec_version = '2', taxation_handling = '1' WHERE pack_id = '28';
INSERT INTO rule_model_pack ( rule_pack_id, rule_model_id ) VALUES ( '28', '31' );
UPDATE rule_pack SET work_state = 'P', state_date = '2015-01-24 00:00:00', rec_version = '3' WHERE rule_pack_id = '28';
